routes/web.php
<?php

use App\Http\Controllers\Application\DashboardController;
use App\Http\Controllers\Application\UserController;
use App\Http\Controllers\Auth\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Authentication
Route::get('/', [AuthController::class, 'index'])->name('login.form');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

Route::prefix('application')->middleware('auth')->group(function() {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    Route::prefix('user')->name('user.')->group(function() {
        Route::get('/', [UserController::class, 'index'])->name('index');
        Route::get('create', [UserController::class, 'create'])->name('create');
        Route::post('store', [UserController::class, 'store'])->name('store');
        Route::get('show/{id}', [UserController::class, 'show'])->name('show');
        Route::put('update/{id}', [UserController::class, 'update'])->name('update');
        Route::delete('delete/{id}', [UserController::class, 'delete'])->name('delete');
        Route::post('approve', [UserController::class, 'approve'])->name('approve');
    });
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'phone',
        'email',
        'password',
        'address',
        'gender',
        'role_id',
        'role_name',
        'location_id',
        'location_name',
        'status',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Application/UserController.php
<?php

namespace App\Http\Controllers\Application;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Http;

class UserController extends Controller
{
    public function index()
    {
        $users = User::orderBy('created_at', 'DESC')->where('name', '!=', 'admin')->get();

        return view('app.user.index',[
            'activePage' => 'Users',
            'users' => $users
        ]);
    }

    public function create() 
    {
        $getLocation = Http::withToken(env('API_TOKEN_AMS'))->get('https://ams.karyaoptima.com/api/public/get-location');
        $locations = [];
        if($getLocation->successful()) {
            $locations = $getLocation->object()->result->data;
        }

        $getRole = Http::withToken(env('API_TOKEN_AMS'))->get('https://ams.karyaoptima.com/api/public/get-role');
        $roles = [];
        if($getRole->successful()) {
            $roles = $getRole->object()->result->data;
        }

        return view('app.user.create', [
            'activePage' => 'Users',
            'locations' => $locations,
            'roles' => $roles,
        ]);
    }

    public function store(Request $request) 
    {
      $this->validate($request, [
        'name' => 'required',
        'phone' => 'required',
        'email' => 'required|email',
        'address' => 'required',
        'gender' => 'required',
        'role' => 'required',
        'location' => 'required',
        // 'password' => 'required',
      ]);

      $explodeRole = explode(',', $request->role);
      $explodeLocation = explode(',', $request->location);

      $user = User::create([
        'name' => $request->name,
        'phone' => $request->phone,
        'email' => $request->email,
        'password' => Hash::make('password'),
        'address' => $request->address,
        'gender' => $request->gender,
        'role_id' => $explodeRole[0],
        'role_name' => $explodeRole[1],
        'location_id' => $explodeLocation[0],
        'location_name' => $explodeLocation[1],
        'status' => 1
      ]);

      return redirect()->route('user.index')->with('success', 'Successfully Created User');
    }

    public function show($id) 
    {
        $user = User::find($id);

        $getLocation = Http::withToken(env('API_TOKEN_AMS'))->get('https://ams.karyaoptima.com/api/public/get-location');
        $locations = [];
        if($getLocation->successful()) {
            $locations = $getLocation->object()->result->data;
        }

        $getRole = Http::withToken(env('API_TOKEN_AMS'))->get('https://ams.karyaoptima.com/api/public/get-role');
        $roles = [];
        if($getRole->successful()) {
            $roles = $getRole->object()->result->data;
        }

        return view('app.user.edit', [
            'activePage' => 'Users',
            'user' => $user,
            'locations' => $locations,
            'roles' => $roles,
        ]);
    }

    public function update(Request $request, $id) 
    {
        $this->validate($request, [
            'name' => 'required',
            'phone' => 'required',
            'email' => 'required|email',
            'address' => 'required',
            'gender' => 'required',
            'role' => 'required',
            'location' => 'required',
            // 'password' => 'required',
        ]);

        $explodeRole = explode(',', $request->role);
        $explodeLocation = explode(',', $request->location);

        $user = User::find($id)->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'email' => $request->email,
            'password' => Hash::make('password'),
            'address' => $request->address,
            'gender' => $request->gender,
            'role_id' => $explodeRole[0],
            'role_name' => $explodeRole[1],
            'location_id' => $explodeLocation[0],
            'location_name' => $explodeLocation[1],
            'status' => 1
        ]);

        // if(! empty($request->password)) {
        //     $user->update([
        //         'password' => Hash::make($request->password)
        //     ]);
        // }

        return redirect()->route('user.index')->with('success', 'Successfully Updated User');
    }

    public function delete($id) 
    {
        User::find($id)->delete();

        return redirect()->back()->with('success', 'Success Deleted User');
    }

    public function approve(Request $request)
    {
        $userIds = explode(',', $request->user_ids);
        User::whereIn('id', $userIds)->update(['status' => 2]);

        return redirect()->back()->with('success', 'Success Approved User');
    }
}

resources/views/app/user/create.blade.php
@extends('app.layout.app')

@section('contents')
<main class="main-content position-relative border-radius-lg ">
    @include('app.layout.partials.navbar')
   <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<i class="fas fa-plus"></i>
						Create User
					</div>
					<div class="card-body">
						@include('auth.layout.partials.alert-message')
						<form method="POST" action="{{ route('user.store') }}">
							@csrf
							<div class="form-group">
								<label>Name</label>
								<input type="name" name="name" class="form-control @error('name') is-invalid @enderror">
								@error('name')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Phone</label>
								<input type="text" maxlength="11" name="phone" class="form-control @error('phone') is-invalid @enderror">
								@error('phone')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Email</label>
								<input type="email" name="email" class="form-control @error('email') is-invalid @enderror">
								@error('email')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Address</label>
								<textarea type="text" name="address" rows="5" class="form-control @error('address') is-invalid @enderror"></textarea> 
								@error('address')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Gender</label>
								<select class="form-select @error('gender') is-invalid @enderror" name="gender">
									<option value="">Select Gender</option>
									<option value="Male">Male</option>
									<option value="Female">Female</option>
								</select>
								@error('gender')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Role</label>
								<select class="form-select @error('role') is-invalid @enderror" name="role">
									<option value="">Select Role</option>
									@foreach($roles as $role)
										<option value="{{ $role->id.','.$role->name }}">{{ $role->name }}</option>
									@endforeach
								</select>
								@error('role')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Location</label>
								<select class="form-select @error('location') is-invalid @enderror" name="location">
									<option value="">Select Location</option>
									@foreach($locations as $location)
										<option value="{{ $location->id.','.$location->name }}">{{ $location->name }}</option>
									@endforeach
								</select>
								@error('location')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							{{-- <div class="form-group">
								<label>Password</label>
								<input type="password" name="password" class="form-control @error('password') is-invalid @enderror">
								@error('password')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div> --}}
							<button class="btn btn-primary" type="submit">Create User</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

@endsection

resources/views/app/user/edit.blade.php
@extends('app.layout.app')

@section('contents')
<main class="main-content position-relative border-radius-lg ">
    @include('app.layout.partials.navbar')
   <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<i class="fas fa-plus"></i>
						Edit {{ $user->name }}
					</div>
					<div class="card-body">
						@include('auth.layout.partials.alert-message')
						<form method="POST" action="{{ route('user.update', $user->id) }}">
							@method('PUT')
							@csrf
							<div class="form-group">
								<label>Name</label>
								<input type="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ $user->name }}">
								@error('name')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Phone</label>
								<input type="text" maxlength="11" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ $user->phone }}">
								@error('phone')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Email</label>
								<input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ $user->email }}">
								@error('email')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Address</label>
								<textarea type="text" name="address" rows="5" class="form-control @error('address') is-invalid @enderror">{{ $user->address }}</textarea> 
								@error('address')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Gender</label>
								<select class="form-select @error('gender') is-invalid @enderror" name="gender">
									<option value="">Select Gender</option>
									<option value="Male" @if($user->gender == 'Male') selected @endif>Male</option>
									<option value="Female" @if($user->gender == 'Female') selected @endif>Female</option>
								</select>
								@error('gender')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Role</label>
								<select class="form-select @error('role') is-invalid @enderror" name="role">
									<option value="">Select Role</option>
									@foreach($roles as $role)
										<option value="{{ $role->id.','.$role->name }}" @if($user->role_id == $role->id) selected @endif>{{ $role->name }}</option>
									@endforeach
								</select>
								@error('role')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Location</label>
								<select class="form-select @error('location') is-invalid @enderror" name="location">
									<option value="">Select Location</option>
									@foreach($locations as $location)
										<option value="{{ $location->id.','.$location->name }}" @if($user->location_id == $location->id) selected @endif>{{ $location->name }}</option>
									@endforeach
								</select>
								@error('location')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							{{-- <div class="form-group">
								<label>Password</label>
								<input type="password" name="password" class="form-control @error('password') is-invalid @enderror" >
								 <small class="form-text text-muted ml-3 mt-2">Leave password blank if you don't want to change the password.</small>
								@error('password')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div> --}}
							<button class="btn btn-primary" type="submit">Update User</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

@endsection

resources/views/app/user/index.blade.php
@extends('app.layout.app')

@section('contents')
<main class="main-content position-relative border-radius-lg ">
    @include('app.layout.partials.navbar')
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
              @if(session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
              @endif
              <div class="d-flex justify-content-between">
                <form class="d-none" method="POST" action="{{ route('user.approve') }}" id="form-approve">
                  @csrf
                </form>
                <a onclick="submitApprove()" class="btn btn-primary">Approve User</a>
                <a href="{{ route('user.create') }}" class="btn btn-outline-primary">Create User</a>
              </div>
              <h6>Users table</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center justify-content-center mb-0">
                  <thead>
                    <tr>
                      <th style="width: 20px;"></th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Name</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Phone</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Email</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Gender</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Address</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Role</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Location</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($users as $user)
                      <tr>
                        <td>
                          @if($user->status == 1)
                            <div class="form-check">
                              <input class="form-check-input" type="checkbox" name="user_ids[]" value="{{ $user->id }}">
                            </div>
                          @endif
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm" style="margin-left: 10px;">{{ $user->name }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm" style="margin-left: 10px;">{{ $user->phone }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->email }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->gender }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->address }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->role_name }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->location_name }}</h6>
                        </td>
                        <td class="align-middle d-flex flex-wrap">
                          <a style="padding:4px 0;" class="btn btn-link text-secondary mb-0" href="{{ route('user.show', $user->id) }}">
                            <i class="fas fa-eye"></i>
                          </a>
                          @if(auth()->user()->id != $user->id)
                            <form id="form-delete-{{ $user->id }}" method="POST" action="{{ route('user.delete', $user->id) }}">
                              @csrf
                              @method('DELETE')
                              <a onclick="confirmationDelete({{ $user->id }})" style="padding:0" class="btn btn-link text-secondary mb-0 mx-2">
                                <i class="fas fa-trash"></i>
                              </a>
                            </form>
                          @endif
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

  <script>
    function submitApprove() {
      let userIds = [];
      $(':checkbox:checked').each(function(i){
        userIds[i] = $(this).val();
      });

      if(userIds.length > 0) {
        const alert = confirm('Are you sure to approve this users ?')
        if(alert) {
          const input = $("<input>").attr("type", "hidden").attr("name", "user_ids").val(userIds);
          $('#form-approve').append(input);
          $('#form-approve').submit()
        }
      }
    }

    function confirmationDelete(id) {
      const alert = confirm('Are you sure to delete this user ?')
      if(alert) {
        $("#form-delete-"+id).submit();
      }
    }
  </script>
@endsection